// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentalMotor.Api.Repository.Persistence;

#nullable disable

namespace RentalMotor.Api.Migrations
{
    [DbContext(typeof(RentalMotorDbContext))]
    partial class RentalMotorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentalMotor.Api.Entities.Cnh", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<List<string>>("CnhCategories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ImagenCnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberCnh")
                        .HasColumnType("integer");

                    b.Property<string>("UserMotorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserMotorId")
                        .IsUnique();

                    b.ToTable("Cnh");
                });

            modelBuilder.Entity("RentalMotor.Api.Entities.ContractUserFoorPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FoorPlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ForecastEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StarDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserMotorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FoorPlanId")
                        .IsUnique();

                    b.HasIndex("UserMotorId")
                        .IsUnique();

                    b.ToTable("contractUserFoorPlans");
                });

            modelBuilder.Entity("RentalMotor.Api.Entities.FoorPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<int>("CountDay")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyPorcent")
                        .HasColumnType("integer");

                    b.Property<decimal>("PenaltyValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("foorPlans");
                });

            modelBuilder.Entity("RentalMotor.Api.Entities.UserMotor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("usersMotors");
                });

            modelBuilder.Entity("RentalMotor.Api.Entities.Cnh", b =>
                {
                    b.HasOne("RentalMotor.Api.Entities.UserMotor", null)
                        .WithOne("Cnh")
                        .HasForeignKey("RentalMotor.Api.Entities.Cnh", "UserMotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalMotor.Api.Entities.ContractUserFoorPlan", b =>
                {
                    b.HasOne("RentalMotor.Api.Entities.FoorPlan", null)
                        .WithOne("ContractUserFoorPlan")
                        .HasForeignKey("RentalMotor.Api.Entities.ContractUserFoorPlan", "FoorPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalMotor.Api.Entities.UserMotor", null)
                        .WithOne("ContractUserFoorPlan")
                        .HasForeignKey("RentalMotor.Api.Entities.ContractUserFoorPlan", "UserMotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalMotor.Api.Entities.FoorPlan", b =>
                {
                    b.Navigation("ContractUserFoorPlan");
                });

            modelBuilder.Entity("RentalMotor.Api.Entities.UserMotor", b =>
                {
                    b.Navigation("Cnh");

                    b.Navigation("ContractUserFoorPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
